### ISSUE TITLE
Typo within Usage

### ISSUE THREAD

**Issue by holtalanm** [snovakovic/vtpw#1]
First off, I want to say: I love this extension.  I was wasting so much time with the performance issues within vetur lately, and using this extension has helped a TON.

I wanted to point out that there is a little typo within the Usage section of the readme:
![vtpw_usage_typo](https://user-images.githubusercontent.com/7315955/67603588-fb708880-f73e-11e9-9dec-91bcfe6aada9.png)

the hotkey says `ctrl+a+,` when it should be `ctrl+alt+,`

Once again, thanks!!  This extension is awesome!

**Comment by emertechie** [comment]
Also on Mac, the default binding seems to be `alt+cmd+L`:

![image](https://user-images.githubusercontent.com/187313/67619008-8d03f700-f820-11e9-96e0-fa2781a549a9.png)

**Comment by snovakovic** [comment]
@holtalanm glad to hear you find it useful! Thanks for pointing out typo should be fixed now. 

@emertechie thanks for pointing about `mac` It was set to `l` instead of `,` by accident. 

![image](https://user-images.githubusercontent.com/6170843/67660291-c2166380-f95e-11e9-9e9e-e89cb2e95bb1.png)

I have set mac to `cmd+alt+,` but even before it was starting with `cmd+alt+l` so not sure why in above screenshot it say `alt+cmd+l` and not `cmd+alt+l`... Would you mind checking with new version is default shortcut set to `cmd+alt+,` or `alt+cmd+,` as I don't have access to mac for testing.
